tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "postgresql@14", restart_service: true
brew "rbenv"
brew "sqlite"
vscode "dbaeumer.vscode-eslint"
vscode "emmanuelbeziat.vscode-great-icons"
vscode "kleber-swf.unity-code-snippets"
vscode "ms-dotnettools.csharp"
vscode "ms-vscode.sublime-keybindings"
vscode "ms-vsliveshare.vsliveshare"
vscode "rebornix.ruby"
vscode "wingrunr21.vscode-ruby"
